name = "football-jp-push-api"
main = "src/index.js"
compatibility_date = "2024-09-25"

[[kv_namespaces]]
binding = "PUSH_SUBSCRIPTIONS"
id = "47da5166a3514c41a66b2e1159e44a69"

# VAPID_PUBLIC_KEY / VAPID_PRIVATE_KEY / VAPID_SUBJECT は wrangler secret put で設定
